-- Add content_draft column to projects table
ALTER TABLE public.projects 
ADD COLUMN IF NOT EXISTS content_draft JSONB;

COMMENT ON COLUMN public.projects.content_draft IS 'Structured content draft generated by Content Editor Agent';
